---
language: java
dist: xenial
os: linux

jdk:
- openjdk8

branches:
  except:
  - gh-pages

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

cache:
  directories:
  - "$HOME/.m2"

before_install:
- mvn clean
- sudo apt-get update
- sudo apt-get install python
- nvm install 12
- npm install -g npm@6.x

install: true

# For a tagged build, we'll set the maven artifact version #.
before_script:
- openssl aes-256-cbc -K $ghost_key -iv $ghost_iv -in .ghostenv.enc -out .ghostenv -d || true
- echo "TRAVIS_TAG = '${TRAVIS_TAG}'"
- >-
      [ -n "${TRAVIS_TAG}" ]
      && mvn versions:set -DnewVersion=${TRAVIS_TAG} -DgenerateBackupPoms=false
      || true

script:
-  if [[ -n "$TRAVIS_TAG" ]]; then mvn deploy $MVN_ARGS; else mvn package $MVN_ARGS; fi
 
before_deploy:
- pip install --user bump2version
- npm install @semantic-release/changelog -g
- npm install @semantic-release/exec -g
- npm install @semantic-release/git -g
- npm install @semantic-release/github -g

deploy:
  - provider: script
    script: npx semantic-release
    cleanup: false
    on:
      branch: master
  # - provider: releases
  #   token: "$GH_TOKEN"
  #   file:
  #     - "modules/findings_api/target/*.jar"
  #     - "modules/notifications_api/target/*.jar"
  #   file_glob: true
  #   cleanup: false
  #   on:
  #     branch: master
